"""
Build script: concatenate local modules into app_single_file.py
- Strips local imports (config, utils, curve, geom, etc.)
- Keeps tkinter, math, random, ezdxf, PIL
- Replaces i18n.XXX with XXX in app code
- Outputs in dependency order with main block
"""

import re
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Module order (dependency order)
MODULES = [
    "config",
    "utils",
    "curve",
    "geom",
    "exporter",
    "street_network",
    "parcel_subdivision",
    "i18n",
    "tensor_field",
    "hyperstreamline",
    "boundary_field",
    "height_field",
    "street_from_hyperstreamlines",
    "app",
]

# Local modules whose imports we strip
LOCAL_MODULES = set(MODULES)

# Imports to keep (module names)
KEEP_IMPORTS = {"tkinter", "math", "random", "ezdxf", "PIL"}


def should_keep_import(line: str) -> bool:
    """Return True if this import line should be kept."""
    stripped = line.strip()
    if not stripped.startswith(("from ", "import ")):
        return True
    # from X import ... -> keep if X in KEEP_IMPORTS
    m = re.match(r"from\s+(\w+)\s+import", stripped)
    if m:
        return m.group(1) in KEEP_IMPORTS
    # import X or import X as Y
    m = re.match(r"import\s+(\w+)", stripped)
    if m:
        return m.group(1) in KEEP_IMPORTS
    return True


def is_local_import_line(line: str) -> bool:
    """Return True if this line is a local import we should strip."""
    stripped = line.strip()
    if not stripped.startswith(("from ", "import ")):
        return False
    m = re.match(r"from\s+(\w+)\s+import", stripped)
    if m:
        return m.group(1) in LOCAL_MODULES
    m = re.match(r"import\s+(\w+)\b", stripped)
    if m:
        return m.group(1) in LOCAL_MODULES
    return False


def strip_imports(content: str) -> str:
    """Remove lines that import from local modules. Handle multi-line imports."""
    lines = content.split("\n")
    result = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if is_local_import_line(line):
            # Skip this line; if it ends with "(" then skip until ")"
            if "(" in line and ")" not in line:
                i += 1
                while i < len(lines) and ")" not in lines[i]:
                    i += 1
                if i < len(lines):
                    i += 1  # skip closing )
            else:
                i += 1
            continue
        result.append(line)
        i += 1
    return "\n".join(result)


def replace_i18n_refs(content: str) -> str:
    """Replace i18n.XXX with XXX in content."""
    # Match i18n.SYMBOL where SYMBOL is a valid identifier
    def repl(m):
        return m.group(1)

    content = re.sub(r"\bi18n\.([A-Za-z_][A-Za-z0-9_]*)\b", repl, content)
    # Special: getattr(i18n, key.upper().replace(" ", "_"), key) -> globals().get(key.upper().replace(" ", "_"), key)
    content = re.sub(
        r"getattr\(i18n,\s*([^,]+),\s*([^)]+)\)",
        r"globals().get(\1, \2)",
        content,
    )
    return content


def main():
    out_lines = []
    out_lines.append('"""Single-file build of Urban Field Generator. Generated by build_single_file.py."""')
    out_lines.append("")

    for mod in MODULES:
        path = os.path.join(SCRIPT_DIR, f"{mod}.py")
        if not os.path.exists(path):
            print(f"Warning: {mod}.py not found, skipping")
            continue
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        content = strip_imports(content)
        if mod == "app":
            content = replace_i18n_refs(content)
        # Remove leading/trailing blank lines from module, add separator
        content = content.strip()
        out_lines.append(f"# --- {mod}.py ---")
        out_lines.append(content)
        out_lines.append("")

    out_lines.append("")
    out_lines.append("if __name__ == \"__main__\":")
    out_lines.append("    UrbanFieldGenerator().run()")

    out_path = os.path.join(SCRIPT_DIR, "app_single_file.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines))
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
